### ISSUE TITLE
How to use a topic and not a token? (FormatException: Invalid radix-10 number)

### ISSUE THREAD

**Issue by kevincowan** [MikeMitterer/dart-fcm-push#4]
I have been able to use this for a token which is great but I'd like to use a topic too.

If I set my token argument as a topic like this
```
final String token = '/topics/all';
```

It works but I see this output
```
Unhandled exception:
FormatException: Invalid radix-10 number (at character 1)
null
^

#0      int._throwFormatException (dart:core/runtime/libintegers_patch.dart:131:5)
#1      int._parseRadix (dart:core/runtime/libintegers_patch.dart:142:16)
#2      int._parse (dart:core/runtime/libintegers_patch.dart:100:12)
#3      int.parse (dart:core/runtime/libintegers_patch.dart:63:12)
#4      FCM.send (file:///Users/kevincowan/.pub-cache/hosted/pub.dartlang.org/fcm_push-1.3.1/lib/fcm_push/fcm.dart:72:24)
<asynchronous suspension>
#5      main (file:///Users/kevincowan/Documents/flutter/send-notifications/dart/send-push.dart:23:40)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Is there anything I need to do with the topic format? I've tried various combinations but no joy yet in terms of resolving that exception.

Many thanks!

**Comment by kevincowan** [comment]
@MikeMitterer If you have any view on this that would be great - thanks!

**Comment by kevincowan** [comment]
It feels like this line needs to change since a topic will not have success set to 1

https://github.com/MikeMitterer/dart-fcm-push/blob/ab6294de2ad9c19a447e20b299e299f176b745ff/lib/fcm_push/fcm.dart#L72

You can see someone has implemented a similar thing here -

https://stackoverflow.com/a/49206352/11362267

**Comment by kevincowan** [comment]
OK - so this table confirms sending a topic will not return `success` and will only have a `message_id` If successful. 

https://firebase.google.com/docs/cloud-messaging/http-server-ref#table6

**Comment by hemangjoshi37a** [comment]
ok

**Comment by hemangjoshi37a** [comment]
have you found any solution to this problem??
